on: [pull_request]
name: benchmark pull requests
jobs:
  runBenchmark:
    name: run benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: run benchmark
        uses: jasonwilliams/criterion-compare-action@move_to_actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
